package com.hackathon.CodeCampfire.modelData;

import lombok.Getter;
import lombok.Setter;

public class ProjectCreateDTO {

    @Getter @Setter
    private String title;
    @Getter @Setter
    private String description;
    @Getter @Setter
    private String category;
    @Getter @Setter
    private String technologies[];
    @Getter @Setter
    private String coAuthors[];
    @Getter @Setter
    private String author;
    @Getter @Setter
    private String gitHub;


    public ProjectsTable toProjectsTable() {
        ProjectsTable project = new ProjectsTable();
        project.setId(null); // ID will be generated by MongoDB
        project.setTitle(this.title);
        project.setDescription(this.description);
        project.setCategory(this.category);
        project.setTechnologies(this.technologies);
        project.setCoAuthors(this.coAuthors);
        project.setAuthor(this.author);
        project.setGitHub(this.gitHub);
        return project;
    }
    
}
