package com.hackathon.CodeCampfire.modelData;


import lombok.Getter;
import lombok.Setter;

public class ChallengeCreateDTO {


    @Getter @Setter
    private String author;
    @Getter @Setter
    private String startDate;
    
    @Getter @Setter
    private String endDate;

    @Getter @Setter
    private String title;

    @Getter @Setter
    private String description;

    @Getter @Setter
    private String[] tags;

    @Getter @Setter
    private String status;    // "open", "closed", "launching_soon"

    @Getter @Setter
    private String prize;


    public Challenges toChallenges() {
        Challenges challenge = new Challenges();
        challenge.setId(null); // ID will be generated by MongoDB
        challenge.setAuthor(this.author);
        challenge.setStartDate(this.startDate);
        challenge.setEndDate(this.endDate);
        challenge.setTitle(this.title);
        challenge.setDescription(this.description);
        challenge.setTags(this.tags);
        challenge.setStatus(this.status);
        challenge.setPrize(this.prize);
        return challenge;
    }

  
    


}
